version: "3"

services:
  cow-proxy:
    build: .
    image: shgoudarzi/cow-proxy:latest
    ports:
      - "8585:7777"
    volumes:
      - "./cow-proxy.conf:/root/.cow/rc"
    restart: always
    container_name: cow-proxy
